name: STP-Checker-Bot

on:
  schedule:
    - cron: '0 0,9 * * *' # 한국 시간 기준 오전 9시, 오후 6시 자동 실행
  workflow_dispatch: # 수동 실행 버튼

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v3에서 v4로 업데이트
      - name: Set up Python
        uses: actions/setup-python@v5 # v4에서 v5로 업데이트
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python stp_checker.py
